List<Map<String, dynamic>> tableData = [
  {'id': '1A', 'isOccupied': true},
  {'id': '1B', 'isOccupied': false},
  {'id': '1C', 'isOccupied': false},
  {'id': '2A', 'isOccupied': false},
  {'id': '2B', 'isOccupied': true},
  {'id': '2C', 'isOccupied': false},
  {'id': '3A', 'isOccupied': false},
  {'id': '3B', 'isOccupied': false},
  {'id': '3C', 'isOccupied': true},
];

List<Map<String, dynamic>> menu = [
  {
    'category': 'Veg',
    'items': [
      {'name': 'Spinach and Artichoke Dip', 'price': 200},
      {'name': 'Vegetable Spring Rolls', 'price': 180},
      {'name': 'Caprese Salad Skewers', 'price': 250},
      {'name': 'Margherita Pizza', 'price': 120},
      {'name': 'Eggplant Parmesan', 'price': 110},
      {'name': 'Vegetable Stir-Fry', 'price': 100},
      {'name': 'Garlic Parmesan Fries', 'price': 400},
      {'name': 'Grilled Vegetables', 'price': 230},
      {'name': 'Quinoa Salad', 'price': 500},
      {'name': 'Classic Cheesecake', 'price': 60},
      {'name': 'Fruit Sorbet', 'price': 400},
      {'name': 'Chocolate Mousse', 'price': 70},
    ],
  },
  {
    'category': 'Non-Veg',
    'items': [
      {'name': 'Chicken Wings (Choice of Sauce)', 'price': 90},
      {'name': 'Shrimp Cocktail', 'price': 130},
      {'name': 'Meatball Sliders', 'price': 110},
      {'name': 'Grilled Salmon with Lemon Butter', 'price': 160},
      {'name': 'Chicken Alfredo Pasta', 'price': 140},
      {'name': 'Steak with Mushroom Sauce', 'price': 180},
      {'name': 'Loaded Potato Skins', 'price': 89},
      {'name': 'Bacon-Wrapped Asparagus', 'price': 79},
      {'name': 'Caesar Salad with Grilled Chicken', 'price': 109},
      {'name': 'Tiramisu', 'price': 69},
      {'name': 'Molten Lava Cake', 'price': 799},
      {'name': 'Pecan Pie', 'price': 89},
    ],
  },
  {
    'category': 'Drinks',
    'items': [
      {'name': 'Virgin Mojito', 'price': 399},
      {'name': 'Berry Smoothie', 'price': 599},
      {'name': 'Iced Green Tea', 'price': 209},
      {'name': 'Classic Margarita', 'price': 79},
      {'name': 'Mojito', 'price': 250},
      {'name': 'Pina Colada', 'price': 89},
      {'name': 'Local Craft Beer', 'price': 499},
      {'name': 'Imported Lager', 'price': 590},
      {'name': 'Stout', 'price': 699},
      {'name': 'Red Wine (Cabernet Sauvignon, Merlot)', 'price': 999},
      {'name': 'White Wine (Chardonnay, Sauvignon Blanc)', 'price': 1099},
      {'name': 'Rosé', 'price': 899},
    ],
  },
];
