List<Map<String, dynamic>> tableData = [
  {'id': '1A', 'isOccupied': true},
  {'id': '1B', 'isOccupied': false},
  {'id': '1C', 'isOccupied': false},
  {'id': '2A', 'isOccupied': false},
  {'id': '2B', 'isOccupied': true},
  {'id': '2C', 'isOccupied': false},
  {'id': '3A', 'isOccupied': false},
  {'id': '3B', 'isOccupied': false},
  {'id': '3C', 'isOccupied': true},
];

List<Map<String, dynamic>> menu = [
  {
    'category': 'Veg',
    'items': [
      'Spinach and Artichoke Dip',
      'Vegetable Spring Rolls',
      'Caprese Salad Skewers',
      'Margherita Pizza',
      'Eggplant Parmesan',
      'Vegetable Stir-Fry',
      'Garlic Parmesan Fries',
      'Grilled Vegetables',
      'Quinoa Salad',
      'Classic Cheesecake',
      'Fruit Sorbet',
      'Chocolate Mousse',
    ],
  },
  {
    'category': 'Non-Veg',
    'items': [
      'Chicken Wings',
      'Shrimp Cocktail',
      'Meatball Sliders',
      'Grilled Salmon with Lemon Butter',
      'Chicken Alfredo Pasta',
      'Steak with Mushroom Sauce',
      'Loaded Potato Skins',
      'Bacon-Wrapped Asparagus',
      'Caesar Salad with Grilled Chicken',
      'Tiramisu',
      'Molten Lava Cake',
      'Pecan Pie',
    ],
  },
  {
    'category': 'Drinks',
    'items': [
      'Virgin Mojito',
      'Berry Smoothie',
      'Iced Green Tea',
      'Classic Margarita',
      'Mojito',
      'Pina Colada',
      'Local Craft Beer',
      'Imported Lager',
      'Stout',
      'Red Wine (Cabernet Sauvignon, Merlot)',
      'White Wine (Chardonnay, Sauvignon Blanc)',
      'Rosé',
    ],
  },
];
